/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netzwerkerfassung;

/**
 *
 * @author Brian
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFBezeichnung = new javax.swing.JTextField();
        jTFRaum = new javax.swing.JTextField();
        jCBGebaeude = new javax.swing.JComboBox();
        jCBHardwaretyp = new javax.swing.JComboBox();
        jBtnSpeichern = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLBezeichnung = new javax.swing.JLabel();
        jLHardwareTyp = new javax.swing.JLabel();
        jLGebaeude = new javax.swing.JLabel();
        jLRaum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFBezeichnung.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFBezeichnung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFBezeichnungActionPerformed(evt);
            }
        });

        jTFRaum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jCBGebaeude.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBGebaeude.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCBHardwaretyp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBHardwaretyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnSpeichern.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSpeichern.setText("Speichern");

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("jButton2");

        jLBezeichnung.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLBezeichnung.setText("Bezeichnung");

        jLHardwareTyp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLHardwareTyp.setText("Hardwaretyp");

        jLGebaeude.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLGebaeude.setText("Gebäude");

        jLRaum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLRaum.setText("Raum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSpeichern, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jLBezeichnung)
                    .addComponent(jTFBezeichnung)
                    .addComponent(jLGebaeude)
                    .addComponent(jCBGebaeude, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLRaum)
                    .addComponent(jLHardwareTyp)
                    .addComponent(jCBHardwaretyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFRaum)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBezeichnung)
                    .addComponent(jLHardwareTyp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBHardwaretyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRaum)
                    .addComponent(jLGebaeude, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRaum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBGebaeude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSpeichern)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFBezeichnungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFBezeichnungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBezeichnungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSpeichern;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBGebaeude;
    private javax.swing.JComboBox jCBHardwaretyp;
    private javax.swing.JLabel jLBezeichnung;
    private javax.swing.JLabel jLGebaeude;
    private javax.swing.JLabel jLHardwareTyp;
    private javax.swing.JLabel jLRaum;
    private javax.swing.JTextField jTFBezeichnung;
    private javax.swing.JTextField jTFRaum;
    // End of variables declaration//GEN-END:variables
}
